#ifdef __cplusplus
extern "C" {
#endif
/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.13 (r6666M) -  1 Mar 2018 15:30
*/
#include "../../ADFirstAidKit/adBuffer.h"
#include <stdlib.h>
#include <math.h>
#include "gmm_fused.h_b-all.h"

/*
  Differentiation of gmm_objective in reverse (adjoint) mode:
   gradient     of useful results: *(**(*qs.arr).arr) *(**(*x.arr).arr)
                *(**(*means.arr).arr) *(**(*ls.arr).arr) gmm_objective
                *(*alphas.arr)
   with respect to varying inputs: *(**(*qs.arr).arr) *(**(*x.arr).arr)
                *(**(*means.arr).arr) *(**(*ls.arr).arr) *(*alphas.arr)
   RW status of diff variables: *(**(*qs.arr).arr):incr *(**(*x.arr).arr):incr
                *(**(*means.arr).arr):incr *(**(*ls.arr).arr):incr
                gmm_objective:in-killed *(*alphas.arr):incr
   Plus diff mem management of: qs:in *qs.arr:in *(*qs.arr):in
                **(*qs.arr).arr:in x:in *x.arr:in *(*x.arr):in
                **(*x.arr).arr:in means:in *means.arr:in *(*means.arr):in
                **(*means.arr).arr:in ls:in *ls.arr:in *(*ls.arr):in
                **(*ls.arr).arr:in alphas:in *alphas.arr:in
*/
// name of top routine:
// gmm_objective
// dependent output variables:
// 
// independent variables:
// 
void gmm_objective_b(array_array_number_t_struct *x, 
        array_array_number_t_struct *xb, array_number_t_struct *alphas, 
        array_number_t_struct *alphasb, array_array_number_t_struct *means, 
        array_array_number_t_struct *meansb, array_array_number_t_struct *qs, 
        array_array_number_t_struct *qsb, array_array_number_t_struct *ls, 
        array_array_number_t_struct *lsb, number_t wishart_gamma, number_t 
        wishart_m, number_t gmm_objectiveb) {
    index_t x266 = x->length;
    index_t x11886 = alphas->length;
    number_t x11865 = -1000;
    number_t x11865b = 0.0;
    int branch;
    number_t gmm_objective;
    for (int idx = 0; idx < alphas->length; ++idx) {
        number_t acc = x11865;
        number_t cur = alphas->arr[idx];
        number_t x11896;
        if (acc > cur) {
            x11896 = acc;
            pushcontrol1b(0);
        } else {
            x11896 = cur;
            pushcontrol1b(1);
        }
        acc = x11896;
        x11865 = acc;
    }
    number_t x11909 = 0;
    number_t x11909b = 0.0;
    for (int idx = 0; idx < x266; ++idx) {
        number_t acc = x11909;
        array_number_t x11878 = x->arr[idx];
        array_number_t x11878b = (array_number_t)0;
        array_number_t x11857b = (array_number_t)0;
        x11878b = xb->arr[idx];
        array_number_t x11857 = x->arr[idx];
        x11857b = xb->arr[idx];
        number_t x11833 = -1000;
        for (int idx0 = 0; idx0 < x11886; ++idx0) {
            number_t acc0 = x11833;
            array_number_t x11874 = ls->arr[idx0];
            array_number_t x11874b = (array_number_t)0;
            array_number_t x11850b = (array_number_t)0;
            x11874b = lsb->arr[idx0];
            array_number_t x11850 = qs->arr[idx0];
            x11850b = qsb->arr[idx0];
            number_t x11897 = 0;
            for (int idx00 = 0; idx00 < x11850->length; ++idx00) {
                number_t acc00 = x11897;
                acc00 = acc00 + x11850->arr[idx00];
                x11897 = acc00;
            }
            number_t x11901 = 0;
            for (int idx00 = 0; idx00 < x11878->length; ++idx00) {
                number_t acc00 = x11901;
                index_t x40 = idx00 - 1;
                number_t x11900 = 0;
                for (int idx000 = 0; idx000 < x11874->length; ++idx000) {
                    number_t acc000 = x11900;
                    index_t j = idx000 - x40*(x40+1)/2;
                    index_t x11898;
                    if (j >= 0)
                        x11898 = j < idx00;
                    else
                        x11898 = 0;
                    number_t x11899;
                    if (x11898) {
                        x11899 = acc000 + x11874->arr[idx000]*(x11878->arr[j]-
                            means->arr[idx0]->arr[j]);
                        pushcontrol1b(0);
                    } else {
                        x11899 = acc000;
                        pushcontrol1b(1);
                    }
                    acc000 = x11899;
                    x11900 = acc000;
                    pushinteger4(j);
                }
                number_t x418 = x11900 + exp(qs->arr[idx0]->arr[idx00])*(
                x11878->arr[idx00]-means->arr[idx0]->arr[idx00]);
                acc00 = acc00 + x418*x418;
                x11901 = acc00;
                pushreal8(x418);
            }
            number_t cur = alphas->arr[idx0] + x11897 - 0.5*x11901;
            number_t x11902;
            if (acc0 > cur) {
                x11902 = acc0;
                pushcontrol1b(0);
            } else {
                x11902 = cur;
                pushcontrol1b(1);
            }
            acc0 = x11902;
            x11833 = acc0;
            pushpointer8(x11874b);
            pushpointer8(x11874);
            pushpointer8(x11850b);
            pushpointer8(x11850);
        }
        number_t x11908 = 0;
        for (int idx0 = 0; idx0 < x11886; ++idx0) {
            number_t acc0 = x11908;
            array_number_t x11870 = qs->arr[idx0];
            array_number_t x11870b = (array_number_t)0;
            array_number_t x11846b = (array_number_t)0;
            x11870b = qsb->arr[idx0];
            array_number_t x11846 = ls->arr[idx0];
            x11846b = lsb->arr[idx0];
            number_t x11903 = 0;
            for (int idx00 = 0; idx00 < x11870->length; ++idx00) {
                number_t acc00 = x11903;
                acc00 = acc00 + x11870->arr[idx00];
                x11903 = acc00;
            }
            number_t x11907 = 0;
            for (int idx00 = 0; idx00 < x11857->length; ++idx00) {
                number_t acc00 = x11907;
                index_t x40 = idx00 - 1;
                number_t x11906 = 0;
                for (int idx000 = 0; idx000 < x11846->length; ++idx000) {
                    number_t acc000 = x11906;
                    index_t j = idx000 - x40*(x40+1)/2;
                    index_t x11904;
                    if (j >= 0)
                        x11904 = j < idx00;
                    else
                        x11904 = 0;
                    number_t x11905;
                    if (x11904) {
                        x11905 = acc000 + x11846->arr[idx000]*(x11857->arr[j]-
                            means->arr[idx0]->arr[j]);
                        pushcontrol1b(0);
                    } else {
                        x11905 = acc000;
                        pushcontrol1b(1);
                    }
                    acc000 = x11905;
                    x11906 = acc000;
                    pushinteger4(j);
                }
                number_t x272 = x11906 + exp(qs->arr[idx0]->arr[idx00])*(
                x11857->arr[idx00]-means->arr[idx0]->arr[idx00]);
                acc00 = acc00 + x272*x272;
                x11907 = acc00;
                pushreal8(x272);
            }
            acc0 = acc0 + exp(alphas->arr[idx0] + x11903 - 0.5*x11907 - x11833
                );
            x11908 = acc0;
            pushpointer8(x11846b);
            pushpointer8(x11846);
            pushpointer8(x11870b);
            pushpointer8(x11870);
            pushreal8(x11907);
            pushreal8(x11903);
        }
        pushpointer8(x11878b);
        pushpointer8(x11878);
        pushreal8(x11833);
        pushreal8(x11908);
        pushpointer8(x11857b);
        pushpointer8(x11857);
    }
    number_t x11910 = 0;
    number_t x11910b = 0.0;
    for (int idx = 0; idx < alphas->length; ++idx) {
        number_t acc = x11910;
        acc = acc + exp(alphas->arr[idx] - x11865);
        x11910 = acc;
    }
    number_t x11913 = 0;
    number_t x11913b = 0.0;
    for (int idx = 0; idx < x11886; ++idx) {
        number_t acc = x11913;
        array_number_t x11882 = qs->arr[idx];
        array_number_t x11882b = (array_number_t)0;
        array_number_t x11861b = (array_number_t)0;
        x11882b = qsb->arr[idx];
        array_number_t x11861 = ls->arr[idx];
        x11861b = lsb->arr[idx];
        number_t x11911 = 0;
        for (int idx0 = 0; idx0 < x11882->length; ++idx0) {
            number_t acc0 = x11911;
            number_t x1078;
            x1078 = exp(x11882->arr[idx0]);
            pushreal8(x1078);
        }
        number_t x11912 = 0;
        for (int idx0 = 0; idx0 < x11861->length; ++idx0) {
            number_t acc0 = x11912;
            number_t x1080 = x11861->arr[idx0];
            pushreal8(x1080);
        }
        pushpointer8(x11861b);
        pushpointer8(x11861);
        pushpointer8(x11882b);
        pushpointer8(x11882);
    }
    x11909b = gmm_objectiveb;
    x11910b = -((double)x266*gmm_objectiveb/x11910);
    x11865b = -((double)x266*gmm_objectiveb);
    x11913b = 0.5*gmm_objectiveb;
    for (int idx = x11886-1; idx > -1; --idx) {
        number_t acc = x11913;
        number_t accb = 0.0;
        array_number_t x11882 = qs->arr[idx];
        array_number_t x11882b = (array_number_t)0;
        array_number_t x11861 = ls->arr[idx];
        array_number_t x11861b = (array_number_t)0;
        number_t x11911 = 0;
        number_t x11911b = 0.0;
        number_t x11912 = 0;
        number_t x11912b = 0.0;
        poppointer8((void **)&x11882);
        poppointer8((void **)&x11882b);
        poppointer8((void **)&x11861);
        poppointer8((void **)&x11861b);
        accb = x11913b;
        x11911b = accb;
        x11912b = accb;
        for (int idx0 = x11861->length-1; idx0 > -1; --idx0) {
            number_t acc0 = x11912;
            number_t acc0b = 0.0;
            number_t x1080 = x11861->arr[idx0];
            number_t x1080b = 0.0;
            popreal8(&x1080);
            acc0b = x11912b;
            x1080b = 2*x1080*acc0b;
            x11861b->arr[idx0] = x11861b->arr[idx0] + x1080b;
            x11912b = acc0b;
        }
        for (int idx0 = x11882->length-1; idx0 > -1; --idx0) {
            number_t acc0 = x11911;
            number_t acc0b = 0.0;
            number_t x1078;
            number_t x1078b;
            popreal8(&x1078);
            acc0b = x11911b;
            x1078b = 2*x1078*acc0b;
            x11882b->arr[idx0] = x11882b->arr[idx0] + exp(x11882->arr[idx0])*
                x1078b;
            x11911b = acc0b;
        }
        x11913b = accb;
    }
    for (int idx = alphas->length-1; idx > -1; --idx) {
        number_t acc = x11910;
        number_t accb = 0.0;
        double tempb;
        accb = x11910b;
        tempb = exp(alphas->arr[idx]-x11865)*accb;
        alphasb->arr[idx] = alphasb->arr[idx] + tempb;
        x11865b = x11865b - tempb;
        x11910b = accb;
    }
    for (int idx = x266-1; idx > -1; --idx) {
        number_t acc = x11909;
        number_t accb = 0.0;
        array_number_t x11878 = x->arr[idx];
        array_number_t x11878b = (array_number_t)0;
        array_number_t x11857 = x->arr[idx];
        array_number_t x11857b = (array_number_t)0;
        number_t x11833 = -1000;
        number_t x11833b = 0.0;
        number_t x11908 = 0;
        number_t x11908b = 0.0;
        poppointer8((void **)&x11857);
        poppointer8((void **)&x11857b);
        popreal8(&x11908);
        popreal8(&x11833);
        poppointer8((void **)&x11878);
        poppointer8((void **)&x11878b);
        accb = x11909b;
        x11908b = accb/x11908;
        x11833b = accb;
        for (int idx0 = x11886-1; idx0 > -1; --idx0) {
            number_t acc0 = x11908;
            number_t acc0b = 0.0;
            array_number_t x11870 = qs->arr[idx0];
            array_number_t x11870b = (array_number_t)0;
            array_number_t x11846 = ls->arr[idx0];
            array_number_t x11846b = (array_number_t)0;
            number_t x11903 = 0;
            number_t x11903b = 0.0;
            number_t x11907 = 0;
            number_t x11907b = 0.0;
            double tempb;
            popreal8(&x11903);
            popreal8(&x11907);
            poppointer8((void **)&x11870);
            poppointer8((void **)&x11870b);
            poppointer8((void **)&x11846);
            poppointer8((void **)&x11846b);
            acc0b = x11908b;
            tempb = exp(alphas->arr[idx0]+x11903-0.5*x11907-x11833)*acc0b;
            alphasb->arr[idx0] = alphasb->arr[idx0] + tempb;
            x11903b = tempb;
            x11907b = -(0.5*tempb);
            x11833b = x11833b - tempb;
            for (int idx00 = x11857->length-1; idx00 > -1; --idx00) {
                number_t acc00 = x11907;
                number_t acc00b = 0.0;
                index_t x40 = idx00 - 1;
                number_t x11906 = 0;
                number_t x11906b = 0.0;
                number_t x272 = x11906 + exp(qs->arr[idx0]->arr[idx00])*(
                x11857->arr[idx00]-means->arr[idx0]->arr[idx00]);
                number_t x272b = 0.0;
                double tempb;
                popreal8(&x272);
                acc00b = x11907b;
                x272b = 2*x272*acc00b;
                tempb = exp(qs->arr[idx0]->arr[idx00])*x272b;
                x11906b = x272b;
                qsb->arr[idx0]->arr[idx00] = qsb->arr[idx0]->arr[idx00] + (
                    x11857->arr[idx00]-means->arr[idx0]->arr[idx00])*exp(qs->
                    arr[idx0]->arr[idx00])*x272b;
                x11857b->arr[idx00] = x11857b->arr[idx00] + tempb;
                meansb->arr[idx0]->arr[idx00] = meansb->arr[idx0]->arr[idx00] 
                    - tempb;
                for (int idx000 = x11846->length-1; idx000 > -1; --idx000) {
                    number_t acc000 = x11906;
                    number_t acc000b = 0.0;
                    index_t j = idx000 - x40*(x40+1)/2;
                    index_t x11904;
                    number_t x11905;
                    number_t x11905b;
                    double tempb;
                    popinteger4(&j);
                    acc000b = x11906b;
                    x11905b = acc000b;
                    popcontrol1b(&branch);
                    if (branch == 0) {
                        tempb = x11846->arr[idx000]*x11905b;
                        acc000b = x11905b;
                        x11846b->arr[idx000] = x11846b->arr[idx000] + (x11857
                            ->arr[j]-means->arr[idx0]->arr[j])*x11905b;
                        x11857b->arr[j] = x11857b->arr[j] + tempb;
                        meansb->arr[idx0]->arr[j] = meansb->arr[idx0]->arr[j] 
                            - tempb;
                    } else
                        acc000b = x11905b;
                    x11906b = acc000b;
                }
                x11907b = acc00b;
            }
            for (int idx00 = x11870->length-1; idx00 > -1; --idx00) {
                number_t acc00 = x11903;
                number_t acc00b = 0.0;
                acc00b = x11903b;
                x11870b->arr[idx00] = x11870b->arr[idx00] + acc00b;
                x11903b = acc00b;
            }
            x11908b = acc0b;
        }
        for (int idx0 = x11886-1; idx0 > -1; --idx0) {
            number_t acc0 = x11833;
            number_t acc0b = 0.0;
            array_number_t x11874 = ls->arr[idx0];
            array_number_t x11874b = (array_number_t)0;
            array_number_t x11850 = qs->arr[idx0];
            array_number_t x11850b = (array_number_t)0;
            number_t x11897 = 0;
            number_t x11897b = 0.0;
            number_t x11901 = 0;
            number_t x11901b = 0.0;
            number_t cur = alphas->arr[idx0] + x11897 - 0.5*x11901;
            number_t curb = 0.0;
            number_t x11902;
            number_t x11902b;
            poppointer8((void **)&x11850);
            poppointer8((void **)&x11850b);
            poppointer8((void **)&x11874);
            poppointer8((void **)&x11874b);
            acc0b = x11833b;
            x11902b = acc0b;
            popcontrol1b(&branch);
            if (branch == 0) {
                acc0b = x11902b;
                curb = 0.0;
            } else {
                curb = x11902b;
                acc0b = 0.0;
            }
            alphasb->arr[idx0] = alphasb->arr[idx0] + curb;
            x11897b = curb;
            x11901b = -(0.5*curb);
            for (int idx00 = x11878->length-1; idx00 > -1; --idx00) {
                number_t acc00 = x11901;
                number_t acc00b = 0.0;
                index_t x40 = idx00 - 1;
                number_t x11900 = 0;
                number_t x11900b = 0.0;
                number_t x418 = x11900 + exp(qs->arr[idx0]->arr[idx00])*(
                x11878->arr[idx00]-means->arr[idx0]->arr[idx00]);
                number_t x418b = 0.0;
                double tempb;
                popreal8(&x418);
                acc00b = x11901b;
                x418b = 2*x418*acc00b;
                tempb = exp(qs->arr[idx0]->arr[idx00])*x418b;
                x11900b = x418b;
                qsb->arr[idx0]->arr[idx00] = qsb->arr[idx0]->arr[idx00] + (
                    x11878->arr[idx00]-means->arr[idx0]->arr[idx00])*exp(qs->
                    arr[idx0]->arr[idx00])*x418b;
                x11878b->arr[idx00] = x11878b->arr[idx00] + tempb;
                meansb->arr[idx0]->arr[idx00] = meansb->arr[idx0]->arr[idx00] 
                    - tempb;
                for (int idx000 = x11874->length-1; idx000 > -1; --idx000) {
                    number_t acc000 = x11900;
                    number_t acc000b = 0.0;
                    index_t j = idx000 - x40*(x40+1)/2;
                    index_t x11898;
                    number_t x11899;
                    number_t x11899b;
                    double tempb;
                    popinteger4(&j);
                    acc000b = x11900b;
                    x11899b = acc000b;
                    popcontrol1b(&branch);
                    if (branch == 0) {
                        tempb = x11874->arr[idx000]*x11899b;
                        acc000b = x11899b;
                        x11874b->arr[idx000] = x11874b->arr[idx000] + (x11878
                            ->arr[j]-means->arr[idx0]->arr[j])*x11899b;
                        x11878b->arr[j] = x11878b->arr[j] + tempb;
                        meansb->arr[idx0]->arr[j] = meansb->arr[idx0]->arr[j] 
                            - tempb;
                    } else
                        acc000b = x11899b;
                    x11900b = acc000b;
                }
                x11901b = acc00b;
            }
            for (int idx00 = x11850->length-1; idx00 > -1; --idx00) {
                number_t acc00 = x11897;
                number_t acc00b = 0.0;
                acc00b = x11897b;
                x11850b->arr[idx00] = x11850b->arr[idx00] + acc00b;
                x11897b = acc00b;
            }
            x11833b = acc0b;
        }
        x11909b = accb;
    }
    for (int idx = alphas->length-1; idx > -1; --idx) {
        number_t acc = x11865;
        number_t accb = 0.0;
        number_t cur = alphas->arr[idx];
        number_t curb = 0.0;
        number_t x11896;
        number_t x11896b;
        accb = x11865b;
        x11896b = accb;
        popcontrol1b(&branch);
        if (branch == 0) {
            accb = x11896b;
            curb = 0.0;
        } else {
            curb = x11896b;
            accb = 0.0;
        }
        alphasb->arr[idx] = alphasb->arr[idx] + curb;
        x11865b = accb;
    }
}
#ifdef __cplusplus
}
#endif