#ifdef __cplusplus
extern "C" {
#endif
/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.13 (r6666M) -  1 Mar 2018 15:30
*/
#include <stdlib.h>
#include <math.h>
#include "gmm_fused.h_d-all.h"

/*
  Differentiation of gmm_objective in forward (tangent) mode:
   variations   of useful results: gmm_objective
   with respect to varying inputs: *(**(*qs.arr).arr) *(**(*x.arr).arr)
                *(**(*means.arr).arr) *(**(*ls.arr).arr) *(*alphas.arr)
   RW status of diff variables: *(**(*qs.arr).arr):in *(**(*x.arr).arr):in
                *(**(*means.arr).arr):in *(**(*ls.arr).arr):in
                gmm_objective:out *(*alphas.arr):in
   Plus diff mem management of: qs:in *qs.arr:in *(*qs.arr):in
                **(*qs.arr).arr:in x:in *x.arr:in *(*x.arr):in
                **(*x.arr).arr:in means:in *means.arr:in *(*means.arr):in
                **(*means.arr).arr:in ls:in *ls.arr:in *(*ls.arr):in
                **(*ls.arr).arr:in alphas:in *alphas.arr:in
*/
// name of top routine:
// gmm_objective
// dependent output variables:
// 
// independent variables:
// 
number_t gmm_objective_d(array_array_number_t_struct *x, 
        array_array_number_t_struct *xd, array_number_t_struct *alphas, 
        array_number_t_struct *alphasd, array_array_number_t_struct *means, 
        array_array_number_t_struct *meansd, array_array_number_t_struct *qs, 
        array_array_number_t_struct *qsd, array_array_number_t_struct *ls, 
        array_array_number_t_struct *lsd, number_t wishart_gamma, number_t 
        wishart_m, number_t *gmm_objective) {
    index_t x266 = x->length;
    index_t x11886 = alphas->length;
    number_t x11865 = -1000;
    number_t x11865d;
    x11865d = 0.0;
    for (int idx = 0; idx < alphas->length; ++idx) {
        number_t acc = x11865;
        number_t accd = x11865d;
        number_t cur = alphas->arr[idx];
        number_t curd = alphasd->arr[idx];
        number_t x11896;
        number_t x11896d;
        if (acc > cur) {
            x11896d = accd;
            x11896 = acc;
        } else {
            x11896d = curd;
            x11896 = cur;
        }
        accd = x11896d;
        acc = x11896;
        x11865d = accd;
        x11865 = acc;
    }
    number_t x11909 = 0;
    number_t x11909d;
    x11909d = 0.0;
    for (int idx = 0; idx < x266; ++idx) {
        number_t acc = x11909;
        number_t accd = x11909d;
        array_number_t x11878 = x->arr[idx];
        array_number_t x11878d = xd->arr[idx];
        array_number_t x11857 = x->arr[idx];
        array_number_t x11857d = xd->arr[idx];
        number_t x11833 = -1000;
        number_t x11833d;
        x11833d = 0.0;
        for (int idx0 = 0; idx0 < x11886; ++idx0) {
            number_t acc0 = x11833;
            number_t acc0d = x11833d;
            array_number_t x11874 = ls->arr[idx0];
            array_number_t x11874d = lsd->arr[idx0];
            array_number_t x11850 = qs->arr[idx0];
            array_number_t x11850d = qsd->arr[idx0];
            number_t x11897 = 0;
            number_t x11897d;
            x11897d = 0.0;
            for (int idx00 = 0; idx00 < x11850->length; ++idx00) {
                number_t acc00 = x11897;
                number_t acc00d = x11897d;
                acc00d = acc00d + x11850d->arr[idx00];
                acc00 = acc00 + x11850->arr[idx00];
                x11897d = acc00d;
                x11897 = acc00;
            }
            number_t x11901 = 0;
            number_t x11901d;
            x11901d = 0.0;
            for (int idx00 = 0; idx00 < x11878->length; ++idx00) {
                number_t acc00 = x11901;
                number_t acc00d = x11901d;
                index_t x40 = idx00 - 1;
                number_t x11900 = 0;
                number_t x11900d;
                x11900d = 0.0;
                for (int idx000 = 0; idx000 < x11874->length; ++idx000) {
                    number_t acc000 = x11900;
                    number_t acc000d = x11900d;
                    index_t j = idx000 - x40*(x40+1)/2;
                    index_t x11898;
                    if (j >= 0)
                        x11898 = j < idx00;
                    else
                        x11898 = 0;
                    number_t x11899;
                    number_t x11899d;
                    if (x11898) {
                        x11899d = acc000d + x11874d->arr[idx000]*(x11878->arr[
                            j]-means->arr[idx0]->arr[j]) + x11874->arr[idx000]
                            *(x11878d->arr[j]-meansd->arr[idx0]->arr[j]);
                        x11899 = acc000 + x11874->arr[idx000]*(x11878->arr[j]-
                            means->arr[idx0]->arr[j]);
                    } else {
                        x11899d = acc000d;
                        x11899 = acc000;
                    }
                    acc000d = x11899d;
                    acc000 = x11899;
                    x11900d = acc000d;
                    x11900 = acc000;
                }
                number_t x418 = x11900 + exp(qs->arr[idx0]->arr[idx00])*(
                x11878->arr[idx00]-means->arr[idx0]->arr[idx00]);
                number_t x418d = x11900d + qsd->arr[idx0]->arr[idx00]*exp(qs->
                arr[idx0]->arr[idx00])*(x11878->arr[idx00]-means->arr[idx0]->
                arr[idx00]) + exp(qs->arr[idx0]->arr[idx00])*(x11878d->arr[
                idx00]-meansd->arr[idx0]->arr[idx00]);
                acc00d = acc00d + x418d*x418 + x418*x418d;
                acc00 = acc00 + x418*x418;
                x11901d = acc00d;
                x11901 = acc00;
            }
            number_t cur = alphas->arr[idx0] + x11897 - 0.5*x11901;
            number_t curd = alphasd->arr[idx0] + x11897d - 0.5*x11901d;
            number_t x11902;
            number_t x11902d;
            if (acc0 > cur) {
                x11902d = acc0d;
                x11902 = acc0;
            } else {
                x11902d = curd;
                x11902 = cur;
            }
            acc0d = x11902d;
            acc0 = x11902;
            x11833d = acc0d;
            x11833 = acc0;
        }
        number_t x11908 = 0;
        number_t x11908d;
        x11908d = 0.0;
        for (int idx0 = 0; idx0 < x11886; ++idx0) {
            number_t acc0 = x11908;
            number_t acc0d = x11908d;
            array_number_t x11870 = qs->arr[idx0];
            array_number_t x11870d = qsd->arr[idx0];
            array_number_t x11846 = ls->arr[idx0];
            array_number_t x11846d = lsd->arr[idx0];
            number_t x11903 = 0;
            number_t x11903d;
            double arg1;
            number_t arg1d;
            x11903d = 0.0;
            for (int idx00 = 0; idx00 < x11870->length; ++idx00) {
                number_t acc00 = x11903;
                number_t acc00d = x11903d;
                acc00d = acc00d + x11870d->arr[idx00];
                acc00 = acc00 + x11870->arr[idx00];
                x11903d = acc00d;
                x11903 = acc00;
            }
            number_t x11907 = 0;
            number_t x11907d;
            x11907d = 0.0;
            for (int idx00 = 0; idx00 < x11857->length; ++idx00) {
                number_t acc00 = x11907;
                number_t acc00d = x11907d;
                index_t x40 = idx00 - 1;
                number_t x11906 = 0;
                number_t x11906d;
                x11906d = 0.0;
                for (int idx000 = 0; idx000 < x11846->length; ++idx000) {
                    number_t acc000 = x11906;
                    number_t acc000d = x11906d;
                    index_t j = idx000 - x40*(x40+1)/2;
                    index_t x11904;
                    if (j >= 0)
                        x11904 = j < idx00;
                    else
                        x11904 = 0;
                    number_t x11905;
                    number_t x11905d;
                    if (x11904) {
                        x11905d = acc000d + x11846d->arr[idx000]*(x11857->arr[
                            j]-means->arr[idx0]->arr[j]) + x11846->arr[idx000]
                            *(x11857d->arr[j]-meansd->arr[idx0]->arr[j]);
                        x11905 = acc000 + x11846->arr[idx000]*(x11857->arr[j]-
                            means->arr[idx0]->arr[j]);
                    } else {
                        x11905d = acc000d;
                        x11905 = acc000;
                    }
                    acc000d = x11905d;
                    acc000 = x11905;
                    x11906d = acc000d;
                    x11906 = acc000;
                }
                number_t x272 = x11906 + exp(qs->arr[idx0]->arr[idx00])*(
                x11857->arr[idx00]-means->arr[idx0]->arr[idx00]);
                number_t x272d = x11906d + qsd->arr[idx0]->arr[idx00]*exp(qs->
                arr[idx0]->arr[idx00])*(x11857->arr[idx00]-means->arr[idx0]->
                arr[idx00]) + exp(qs->arr[idx0]->arr[idx00])*(x11857d->arr[
                idx00]-meansd->arr[idx0]->arr[idx00]);
                acc00d = acc00d + x272d*x272 + x272*x272d;
                acc00 = acc00 + x272*x272;
                x11907d = acc00d;
                x11907 = acc00;
            }
            arg1d = alphasd->arr[idx0] + x11903d - 0.5*x11907d - x11833d;
            arg1 = alphas->arr[idx0] + x11903 - 0.5*x11907 - x11833;
            acc0d = acc0d + arg1d*exp(arg1);
            acc0 = acc0 + exp(arg1);
            x11908d = acc0d;
            x11908 = acc0;
        }
        accd = accd + x11908d/x11908 + x11833d;
        acc = acc + (log(x11908) + x11833);
        x11909d = accd;
        x11909 = acc;
    }
    number_t x11910 = 0;
    number_t x11910d;
    x11910d = 0.0;
    for (int idx = 0; idx < alphas->length; ++idx) {
        number_t acc = x11910;
        number_t accd = x11910d;
        accd = accd + (alphasd->arr[idx]-x11865d)*exp(alphas->arr[idx]-x11865)
        ;
        acc = acc + exp(alphas->arr[idx] - x11865);
        x11910d = accd;
        x11910 = acc;
    }
    number_t x11913 = 0;
    number_t x11913d;
    x11913d = 0.0;
    for (int idx = 0; idx < x11886; ++idx) {
        number_t acc = x11913;
        number_t accd = x11913d;
        array_number_t x11882 = qs->arr[idx];
        array_number_t x11882d = qsd->arr[idx];
        array_number_t x11861 = ls->arr[idx];
        array_number_t x11861d = lsd->arr[idx];
        number_t x11911 = 0;
        number_t x11911d;
        x11911d = 0.0;
        for (int idx0 = 0; idx0 < x11882->length; ++idx0) {
            number_t acc0 = x11911;
            number_t acc0d = x11911d;
            number_t x1078;
            number_t x1078d;
            x1078d = x11882d->arr[idx0]*exp(x11882->arr[idx0]);
            x1078 = exp(x11882->arr[idx0]);
            acc0d = acc0d + x1078d*x1078 + x1078*x1078d;
            acc0 = acc0 + x1078*x1078;
            x11911d = acc0d;
            x11911 = acc0;
        }
        number_t x11912 = 0;
        number_t x11912d;
        x11912d = 0.0;
        for (int idx0 = 0; idx0 < x11861->length; ++idx0) {
            number_t acc0 = x11912;
            number_t acc0d = x11912d;
            number_t x1080 = x11861->arr[idx0];
            number_t x1080d = x11861d->arr[idx0];
            acc0d = acc0d + x1080d*x1080 + x1080*x1080d;
            acc0 = acc0 + x1080*x1080;
            x11912d = acc0d;
            x11912 = acc0;
        }
        accd = accd + x11911d + x11912d;
        acc = acc + (x11911 + x11912);
        x11913d = accd;
        x11913 = acc;
    }
    *gmm_objective = x11909 - (double)x266*(log(x11910)+x11865) + 0.5*x11913;
    return x11909d - (double)x266*(x11910d/x11910+x11865d) + 0.5*x11913d;
}
#ifdef __cplusplus
}
#endif