/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.13 (r6666M) -  1 Mar 2018 15:30
*/
/*
  Differentiation of vec_add in forward (tangent) mode:
   variations   of useful results: alloc(*res)
   with respect to varying inputs: alloc(*res) *x *y
   RW status of diff variables: alloc(*res):in-out *x:in *y:in
   Plus diff mem management of: x:in y:in
*/
double * vec_add_d(int n, double *x, double *xd, double *y, double *yd, double
        **vec_add) {
    double *res;
    double *resd;
    int ii1;
    resd = (double *)malloc(n*sizeof(double));
    for (ii1 = 0; ii1 < n; ++ii1)
        resd[ii1] = 0.0;
    res = (double *)malloc(n*sizeof(double));
    for (int i = 0; i < n; ++i) {
        resd[i] = xd[i] + yd[i];
        res[i] = x[i] + y[i];
    }
    *vec_add = res;
    return resd;
}
/*
  Differentiation of vec_elem_mult in forward (tangent) mode:
   variations   of useful results: alloc(*res)
   with respect to varying inputs: alloc(*res) *x *y
   RW status of diff variables: alloc(*res):in-out *x:in *y:in
   Plus diff mem management of: x:in y:in
*/
double * vec_elem_mult_d(int n, double *x, double *xd, double *y, double *yd, 
        double **vec_elem_mult) {
    double *res;
    double *resd;
    int ii1;
    resd = (double *)malloc(n*sizeof(double));
    for (ii1 = 0; ii1 < n; ++ii1)
        resd[ii1] = 0.0;
    res = (double *)malloc(n*sizeof(double));
    for (int i = 0; i < n; ++i) {
        resd[i] = xd[i]*y[i] + x[i]*yd[i];
        res[i] = x[i]*y[i];
    }
    *vec_elem_mult = res;
    return resd;
}
/*
  Differentiation of vec_scal_mult in forward (tangent) mode:
   variations   of useful results: alloc(*res)
   with respect to varying inputs: y
   RW status of diff variables: alloc(*res):out y:in
*/
double * vec_scal_mult_d(int n, double *x, double y, double yd, double **
        vec_scal_mult) {
    double *res;
    double *resd;
    resd = (double *)malloc(n*sizeof(double));
    res = (double *)malloc(n*sizeof(double));
    for (int i = 0; i < n; ++i) {
        resd[i] = x[i]*(yd*y+y*yd);
        res[i] = x[i]*y*y;
    }
    *vec_scal_mult = res;
    return resd;
}