/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
*/
typedef double number_t;
typedef struct array_number_t_struct {
    number_t *arr;
    int length;
} * array_number_t;

/*
  Differentiation of cross in forward (tangent) mode:
   variations   of useful results: alloc(*(*array40.arr)) *(alloc(*array40).arr)
   with respect to varying inputs: alloc(*(*array40.arr)) *(alloc(*array40).arr)
                *(*a.arr) *(*b.arr)
   RW status of diff variables: alloc(*(*array40.arr)):in-out
                *(alloc(*array40).arr):in-out *(*a.arr):in *(*b.arr):in
   Plus diff mem management of: alloc(*array40).arr:in-out a:in
                *a.arr:in b:in *b.arr:in
*/
array_number_t cross_d(array_number_t_struct *a, array_number_t_struct *ad, 
        array_number_t_struct *b, array_number_t_struct *bd, array_number_t *
        cross) {
    array_number_t array40;
    array_number_t array40d;
    array40d = (array_number_t)malloc(sizeof(int)*2);
    array40 = (array_number_t)malloc(sizeof(int)*2);
    array40->length = 3;
    array40d->arr = (number_t *)malloc(sizeof(number_t)*3);
    array40->arr = (number_t *)malloc(sizeof(number_t)*3);
    array40d->arr[0] = ad->arr[1]*b->arr[2] + a->arr[1]*bd->arr[2] - ad->arr[2
        ]*b->arr[1] - a->arr[2]*bd->arr[1];
    array40->arr[0] = a->arr[1]*b->arr[2] - a->arr[2]*b->arr[1];
    array40d->arr[1] = ad->arr[2]*b->arr[0] + a->arr[2]*bd->arr[0] - ad->arr[0
        ]*b->arr[2] - a->arr[0]*bd->arr[2];
    array40->arr[1] = a->arr[2]*b->arr[0] - a->arr[0]*b->arr[2];
    array40d->arr[2] = ad->arr[0]*b->arr[1] + a->arr[0]*bd->arr[1] - ad->arr[1
        ]*b->arr[0] - a->arr[1]*bd->arr[0];
    array40->arr[2] = a->arr[0]*b->arr[1] - a->arr[1]*b->arr[0];
    *cross = array40;
    return array40d;
}
