/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
*/
typedef double number_t;
typedef struct array_number_t_struct {
    number_t *arr;
    int length;
} * array_number_t;

/*
  Differentiation of dot_prod in forward (tangent) mode:
   variations   of useful results: dot_prod
   with respect to varying inputs: *(*a.arr) *(*b.arr)
   RW status of diff variables: dot_prod:out *(*a.arr):in *(*b.arr):in
   Plus diff mem management of: a:in *a.arr:in b:in *b.arr:in
*/
number_t dot_prod_d(array_number_t_struct *a, array_number_t_struct *ad, 
        array_number_t_struct *b, array_number_t_struct *bd, number_t *
        dot_prod) {
    number_t macroDef26 = 0;
    number_t macroDef26d;
    macroDef26d = 0.0;
    for (int cur_idx = 0; cur_idx < a->length; ++cur_idx) {
        macroDef26d = macroDef26d + ad->arr[cur_idx]*b->arr[cur_idx] + a->arr[
            cur_idx]*bd->arr[cur_idx];
        macroDef26 = macroDef26 + a->arr[cur_idx]*b->arr[cur_idx];
    }
    *dot_prod = macroDef26;
    return macroDef26d;
}
