/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
*/
typedef double number_t;
typedef struct array_number_t_struct {
    number_t *arr;
    int length;
} * array_number_t;
typedef int card_t;
typedef number_t (*lambda_t)();
typedef void * env_t;
typedef int empty_env_t;
typedef struct closure_t {
    lambda_t lam;
    env_t env;
} closure_t;
typedef struct {
    void *env;
} closure_t_d;

/*
  Differentiation of TOP_LEVEL_linalg_vectorMap2 in forward (tangent) mode:
   variations   of useful results: alloc(*(*macroDef13.arr)) *(alloc(*macroDef13).arr)
                *(f.env)
   with respect to varying inputs: alloc(*(*macroDef13.arr)) *(alloc(*macroDef13).arr)
                *(f.env) *(*v1.arr) *(*v2.arr)
   RW status of diff variables: alloc(*(*macroDef13.arr)):in-out
                *(alloc(*macroDef13).arr):in-out *(f.env):in-out
                *(*v1.arr):in *(*v2.arr):in
   Plus diff mem management of: alloc(*macroDef13).arr:in-out
                v1:in *v1.arr:in v2:in *v2.arr:in
*/
array_number_t TOP_LEVEL_linalg_vectorMap2_d(closure_t f, closure_t_d fd, 
        array_number_t_struct *v1, array_number_t_struct *v1d, 
        array_number_t_struct *v2, array_number_t_struct *v2d, array_number_t 
        *TOP_LEVEL_linalg_vectorMap2) {
    card_t macroDef12 = v1->length;
    array_number_t macroDef13;
    array_number_t macroDef13d;
    macroDef13d = (array_number_t)malloc(sizeof(int)*2);
    macroDef13 = (array_number_t)malloc(sizeof(int)*2);
    macroDef13->length = macroDef12;
    macroDef13d->arr = (number_t *)malloc(sizeof(number_t)*macroDef12);
    macroDef13->arr = (number_t *)malloc(sizeof(number_t)*macroDef12);
    for (int i = 0; i < macroDef13->length; ++i) {
        macroDef13d->arr[i] = f.lam_d(f.env, fd.env, v1->arr[i], v1d->arr[i], 
                                      v2->arr[i], v2d->arr[i], &macroDef13->
                                      arr[i]);
        v2d->arr[i] = 0.0;
        v1d->arr[i] = 0.0;
    }
    *TOP_LEVEL_linalg_vectorMap2 = macroDef13;
    return macroDef13d;
}
